# Generated by Django 5.1.6 on 2025-02-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_account_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simcard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
